---
title: "Untitled"
format: html
editor: visual
---

## Pearls Assignment 1

Objectives:

-   Explain the features that all mollusks have in common and the features that make them different

-   Understand the basics of mollusk anatomy and cultured pearl structure

-   Understand the history of natural pearls and how it relates to modern cultured pearl production

-   Define the four main types of cultured pearls and their sources

-   Recognize the characteristics that make a pearl beautiful and determine its value

Details:

**Mollusks**

1\) Bivalves: two shells joined by a hinge

2\) Univalves: single shell and no hinge; contain gastropods ( 腹足类动物), such as land and sea snails

3\) Without shells: squid and octopus

**Four major cultured pearl types in the marketplace:**

1\) Akoya, 2) Freshwater, 3) South Sea, 4) Tahitian

### Pearl Composition and Structure

Mantle, mother of pearl (nacre)

Nacre is made up mostly conchiolin and layers of calcium carbonate platelets

Another effect of nacre\'s extremely thin layers is that white light sometimes travels through it at different speeds and in different directions. This causes light to break up into its component spectral colors, creating an iridescent rainbow effect.

### **Different kinds of pearls**

1.  **Nacreous Pearls from Abalone**: Some of the most striking and unusual pearls in the world come from abalone mollusks
2.  The conch and Melo melo snail---both univalve mollusks---produce **non-nacreous natural pearls**. Because they\'re not \"true\" pearls, they\'re sometimes called calcareous concretions:
    1.  Conch pearls: very rare, Conch pearls are usually small and rarely spherical.
    2.  Melo melo pearls: Melo pearls are rare, natural, and non-nacreous. Melo pearls are often spherical, and they can be quite large
3.  
